import type { StorageQuota } from '../../provider-interface';

/**
 * MEGA storage-upgrade referral offer.
 *
 * Configured via VITE_MEGA_REFERRAL_URL (paste the link generated by MEGA's
 * referral dashboard verbatim). When unset, no upgrade link is ever rendered —
 * same opt-in pattern as VITE_ONEDRIVE_CLIENT_ID, so forks and deploys never
 * inherit someone else's referral code by accident.
 */

/** Offer the upgrade once usage reaches the quota bar's warning color. */
export const MEGA_UPGRADE_OFFER_THRESHOLD = 0.8;

const MEGA_HOSTS = ['mega.nz', 'mega.io'];

/**
 * The configured referral URL, or null when unset or not an https MEGA link.
 * The host check is a misconfiguration guard: the app should never render an
 * "upgrade MEGA" link that leads anywhere but MEGA.
 */
export function getMegaReferralUrl(
  env: Record<string, string | undefined> = import.meta.env
): string | null {
  const url = env?.VITE_MEGA_REFERRAL_URL;
  if (typeof url !== 'string' || url === '') return null;
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'https:') return null;
    const host = parsed.hostname.toLowerCase();
    if (!MEGA_HOSTS.some((h) => host === h || host.endsWith(`.${h}`))) return null;
  } catch {
    return null;
  }
  return url;
}

/** True when a referral link is configured and usage is at/above the threshold. */
export function shouldOfferMegaUpgrade(
  quota: StorageQuota | null,
  referralUrl: string | null
): boolean {
  if (!referralUrl || !quota || quota.total === null || quota.total <= 0) return false;
  return quota.used / quota.total >= MEGA_UPGRADE_OFFER_THRESHOLD;
}
